'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Plus, Minus } from 'lucide-react';

const breads = [
 {n:'Das Isarbrot',s:'Roggen · Sauerteig · Zeit',d:'Eine dunkle, kräftige Kruste. Eine saftige Mitte. Unser Brot für den Alltag – und für das zweite Stück.',tag:'Unser Signaturbrot'},
 {n:'Die goldene Brezn',s:'Lauge · Butter · Meersalz',d:'Ein feiner Bauch, knusprige Arme und genau die richtige Prise Salz. München, auf die Hand.',tag:'Münchner Morgen'},
 {n:'Das Wochenendstück',s:'Weizen · Butter · Schichten',d:'Blättrig, duftend und am liebsten noch ein bisschen warm. Für einen Morgen ohne Eile.',tag:'Kleine Auszeit'}
];
export default function Home(){
 const [menu,setMenu]=useState(false); const [faq,setFaq]=useState<number|null>(null);
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:0.08});document.querySelectorAll('[data-reveal]').forEach(e=>{e.classList.add('reveal-ready');observer.observe(e)});return()=>observer.disconnect()},[]);
 return <>
 <header className="header"><a className="wordmark" href="#start" aria-label="ISARGOLD Startseite"><span className="brand-symbol">i.</span> ISARGOLD<span className="wordmark-sub">MÜNCHNER BACKKULTUR</span></a><nav aria-label="Hauptnavigation" className={menu?'nav open':'nav'}><a href="#handwerk" onClick={()=>setMenu(false)}>Unser Handwerk</a><a href="#sortiment" onClick={()=>setMenu(false)}>Brot & mehr</a><a href="/baeckereimuenchen/buch/">Das Buch <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" aria-label={menu?'Menü schließen':'Menü öffnen'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="start"><section className="hero"><div className="hero-kicker"><span>GUTES BROT. GUTE HALTUNG.</span><span>MÜNCHEN / AN DER ISAR</span></div><h1>Für die Kruste.<br/><em>Fürs Leben.</em></h1><div className="hero-bottom"><p>Wir glauben an das Einfache.<br/>Gutes Mehl. Viel Zeit. Echtes Handwerk.</p><a className="round-link" href="#handwerk" aria-label="Unser Handwerk entdecken"><ArrowDown/></a><span className="hero-side">HANDWERK MIT HERZ<br/>UND EIN BISSCHEN EIGENSINN.</span></div><div className="hero-photo"><img src="/baeckereimuenchen/images/bread.webp" alt="Goldbraunes Sauerteigbrot mit kräftiger Kruste auf einem dunklen Backtisch" fetchPriority="high" width="1536" height="1024"/><span className="photo-caption">Weniger Zutaten. Mehr Charakter.</span></div></section>
 <div className="ticker" aria-label="Unsere Werte"><span>MEHL. WASSER. SALZ. ZEIT.</span><span aria-hidden="true">✳</span><span>NICHT MEHR. NICHT WENIGER.</span><span aria-hidden="true">✳</span></div>
 <section id="handwerk" className="craft section"><div className="section-label">01 / WAS UNS ANTREIBT</div><div className="craft-grid"><h2 data-reveal>Gutes Brot<br/>kennt keine<br/><em>Abkürzung.</em></h2><div className="craft-copy" data-reveal><p className="lead">Die besten Dinge entstehen, wenn man ihnen Raum gibt.</p><p>Wir denken Backen vom Teig aus. Vom Gefühl in den Händen. Vom Duft, der verrät, wann es richtig ist. Und von den Menschen, die später gemeinsam am Tisch sitzen.</p><p>ISARGOLD ist unser Entwurf einer Münchner Backstube: verwurzelt im Handwerk, offen für neue Ideen. Mit Broten, die nicht laut sein müssen, um in Erinnerung zu bleiben.</p><a className="text-link" href="#sortiment">Unsere Lieblingsstücke <ArrowUpRight size={20}/></a></div></div><figure className="craft-image" data-reveal><img src="/baeckereimuenchen/images/hands.webp" alt="Mehlbestäubte Hände formen einen Brotteig auf einer Holzarbeitsfläche" loading="lazy" width="1536" height="1024"/><figcaption>Mit den Händen denken.</figcaption></figure></section>
 <section id="sortiment" className="bread-section section"><div className="section-label">02 / BROT & MEHR</div><div className="section-heading"><h2>Wenig Schnickschnack.<br/><em>Viel Geschmack.</em></h2><p>Drei Lieblingsstücke.<br/>Eine gemeinsame Haltung.</p></div><div className="bread-grid">{breads.map((b,i)=><article className="bread-card" key={b.n} data-reveal><div className="bread-number">0{i+1}<span>{b.tag}</span></div><h3>{b.n}</h3><p className="ingredients">{b.s}</p><p>{b.d}</p></article>)}</div><p className="fine-note">Eine fiktive Sortimentsskizze. Zutaten und Allergene wären vor einem echten Verkauf verbindlich auszuweisen.</p></section>
 <section className="book-feature"><img src="/baeckereimuenchen/images/book.webp" alt="Offenes Buch neben Brot und Butter im warmen Morgenlicht" loading="lazy" width="1536" height="1024"/><div className="book-shade"/><div className="book-content" data-reveal><span className="section-label">03 / EIN BUCH, DAS WEITERDENKT</span><h2>Kruste<br/>& Haltung.</h2><p>Was Backen, Bewegung und Lernen verbindet?<br/>Es beginnt immer mit dem ersten Versuch.</p><a className="button gold" href="/baeckereimuenchen/buch/">Ins Buch schauen <ArrowUpRight size={20}/></a><span className="book-note">Ein unabhängiges Buchkonzept mit Leseprobe.</span></div></section>
 <section className="ritual section"><span className="section-label">04 / KLEINE RITUALE</span><h2 data-reveal>Ein guter Morgen<br/>braucht <em>nicht viel.</em></h2><div className="ritual-grid"><p className="lead">Ein Stück Brot. Ein freier Moment. Und die Lust, etwas mit den eigenen Händen zu machen.</p><div>{[{q:'Was steckt hinter ISARGOLD?',a:'ISARGOLD ist eine fiktive Münchner Bäckerei als vollständig ausgearbeitetes Marken- und Websitekonzept. Es gibt hier noch kein Ladengeschäft und keinen Verkauf.'},{q:'Kann ich hier Brot bestellen?',a:'Noch nicht. Die Seite zeigt ein mögliches Sortiment. Sobald aus dem Konzept eine echte Backstube wird, können Abholung, Verfügbarkeit und verbindliche Preise ergänzt werden.'},{q:'Was hat es mit dem Buch auf sich?',a:'„Kruste & Haltung“ verbindet Backhandwerk mit alltagstauglichen Gedanken zu Übung, Bewegung und Lernen. Die Leseprobe ist kostenlos verfügbar. Eine mögliche Zusammenarbeit mit Lars Riedel oder FUU ist eine Idee, keine bestätigte Kooperation.'}].map((f,i)=><div className="faq" key={f.q}><button aria-expanded={faq===i} aria-controls={'answer-'+i} onClick={()=>setFaq(faq===i?null:i)}>{f.q}{faq===i?<Minus size={20}/>:<Plus size={20}/>}</button><div id={'answer-'+i} hidden={faq!==i}><p>{f.a}</p></div></div>)}</div></div></section>
 </main><footer><div className="footer-top"><span>BLEIB NEUGIERIG.<br/>BLEIB HUNGRIG.</span><a href="#start" aria-label="Zurück zum Anfang"><ArrowUpRight size={36}/></a></div><div className="footer-brand">ISARGOLD</div><div className="footer-bottom"><span>Münchner Backkultur · Fiktives Demoprojekt</span><a href="/baeckereimuenchen/isargold-markenpaket.zip" download>Markenpaket herunterladen</a><span>Keine Bestellungen · Keine Datenerfassung durch Formulare</span></div></footer></>;
}
